### PR TITLE
Add AUTHORS file to the project

### PR DESCRIPTION
**Pull request by andreagrandi**
@alessio @astagi please could you tell me which email do you prefer me to add next to your name? Thanks

### CODE REVIEW

**Comment by astagi** [comment]
@andreagrandi stagi.andrea :smile: :+1:

**Comment by andreagrandi** [comment]
@alessio @astagi PR updated. Please review and tell me if/when I can merge, cheers

**Comment by alessio** [comment]
:+1: ACK

**Comment by astagi** [comment]
LGTM!

Andrea, Andrea, Alessio.. The A-Team

**Comment by alessio** [comment]
> Andrea, Andrea, Alessio.. The A-Team

Where the hell did they place the fucking "Like" button on this GitHub-thing?

**Comment by andreagrandi** [comment]
We have a triple A that not even German economy :D

**Pull request merged**
