### PR TITLE
Use flag module to parse command line args

### LINKED ISSUE #15: Refactor service parameters to use flag
Parameters should be passed using **flag** library: https://gobyexample.com/command-line-flags

p.s: I'm working on this ticket already

### PR DESCRIPTION
**Pull request by andreagrandi**
Use flag module to parse command line args and refactor a few variables to follow Golang casing convention.

Fixes #15

### CODE REVIEW

**Comment by andreagrandi** [comment]
@alessio @astagi calling for review, cheers

**Comment by alessio** [comment]
I wonder why you squashed all commits onto a single one. I think it's a good practice to keep changes consistent and actually the sole commit your branch contains does not document the cosmetic fixes you applied along with the primary functional change (namely the use of "flag module to parse command line args"). In other words, I'd like to see 2 commits (no matters in which order):
- Use flag module to parse command line
- Cosmetic fixes

If you think I'm nitpicking, just ignore this comment and go on though :)

**Comment by andreagrandi** [comment]
@alessio the point is that I should have left those other changes alone, but the linter inside Atom looked so sad that I wanted to make it happier :P 

Also: now that I squashed and push -f 'ed the changes, I can't roll back.

Let's leave this as-is for this time and I will create a specific ticket with linter refactoring where all the rest will go.

p.s: so I go on merging, ok?

**Comment by alessio** [comment]
It's nihil obstat from me, please merge.

**Pull request merged**
